use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct SystemInfo {
    pub compiled_backend: String,
    pub os: String,
    pub arch: String,
}

#[tauri::command]
pub fn get_system_info() -> SystemInfo {
    SystemInfo {
        compiled_backend: if cfg!(feature = "cuda") {
            "cuda"
        } else if cfg!(feature = "metal") {
            "metal"
        } else {
            "cpu"
        }
        .to_string(),
        os: std::env::consts::OS.to_string(),
        arch: std::env::consts::ARCH.to_string(),
    }
}

#[tauri::command]
pub fn get_app_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

#[tauri::command]
pub fn get_licenses() -> Result<String, String> {
    // Read THIRD_PARTY_LICENSES.txt from app resources
    // For now, return placeholder
    Ok("Third-party licenses will be generated by cargo-about.\n\nstable-diffusion.cpp - Copyright (c) 2023 leejet - MIT License".into())
}
